export const SIGN_IN = 'SIGN_IN';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_ERROR = 'SIGN_ERROR';

export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_CONTACTS_PENDING = 'GET_CONTACTS_PENDING';
export const GET_CONTACTS_REJECTED = 'GET_CONTACTS_REJECTED';
export const GET_CONTACTS_FULFILLED = 'GET_CONTACTS_FULFILLED';

export const SEARCH_CONTACTS = 'SEARCH_CONTACTS';
export const SEARCH_CONTACTS_PENDING = 'SEARCH_CONTACTS_PENDING';
export const SEARCH_CONTACTS_REJECTED = 'SEARCH_CONTACTS_REJECTED';
export const SEARCH_CONTACTS_FULFILLED = 'SEARCH_CONTACTS_FULFILLED';

export const DELETE_CONTACT = 'DELETE_CONTACTS';
export const DELETE_CONTACT_ERROR = 'DELETE_CONTACT_ERROR';